### ISSUE TITLE
Exception - Permission Denial

### ISSUE THREAD

**Issue by AliAlHourash** [ivehement/saf#10]
This exception appear when I try to open media directory

_Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fmedia%2Fcom.whatsapp%2FWhatsApp%2FMedia%2F.Statuses/document/primary%3AAndroid%2Fmedia%2Fcom.whatsapp%2FWhatsApp%2FMedia%2F.Statuses/children from pid=32755, uid=10159 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs_

**Comment by Stephen-Cronin** [comment]
@AliAlHourash - Out of interest, why did you close this? Did you solve the problem? I'm having the same thing.

**Comment by milesegan** [comment]
I'm also getting this error if I try to open the root directory like this:

```dart
final _saf = Saf("");
```

If I give it a more specific subpath then it seems to work:
```dart
final _saf = Saf("Music");
```

**Comment by milesegan** [comment]
It also works if I use an empty initial directory but pass `isDynamic: true`:

```dart
final _saf = Saf("");
final isGranted = await _saf.getDirectoryPermission(isDynamic: true);
```
