### ISSUE TITLE
Incorrect dependencies

### ISSUE THREAD

**Issue by gorkovv** [ivehement/saf#14]
Running "flutter pub get" in appnote...                         
Because every version of saf depends on permission_handler ^9.2.0 and appnote depends on permission_handler ^10.0.0, saf is forbidden.
So, because appnote depends on saf ^1.0.3+3, version solving failed.
pub get failed (1; So, because appnote depends on saf ^1.0.3+3, version solving failed.)

**Comment by provokateurin** [comment]
Hi, I fixed it in https://github.com/jld3103/saf/commit/777a1177763eaa6d106224714c8cf94020a7257f
