### ISSUE TITLE
Can't use this folder to protect your privacy choose another folder ....!!!

### ISSUE THREAD

**Issue by HussnulMaab192** [ivehement/saf#21]
I am unable to access **.statuses** folder directly. When I click on the **"grant button"** it does not directly open the ,statuses folder and open the root directory and the **"use this folder" button is unclickable**. User have to open manually this folder to get access. 

here is the directory which I want to access:
 saf = Saf( '/storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/.Statuses');
![WhatsApp Image 2022-11-16 at 7 56 33 PM](https://user-images.githubusercontent.com/100747559/202214753-34b92f99-b04a-49a4-ac22-d03035920146.jpeg)

**Comment by HussnulMaab192** [comment]
I just recognized that if we initialize path "Android/media/com.whatsapp/WhatsApp/Media/.Statuses" then it allows us to access directly this directory!
but not able to get this permission less then android 11.

**Comment by Rambhaiahir** [comment]
how to initialize same problem im facing how to solve ?

**Comment by jvoltci** [comment]
Android less than 11 don't need permission to access. Above Android 11, access can be given the same way.
