### ISSUE TITLE
Wiki / API documentation is broken

### ISSUE THREAD

**Issue by kankaristo** [ivehement/saf#9]
All of the links that point to the API documentation (GitHub Wiki) just redirect to the repository's front page. So effectively, there is no API documentation, making the package a bit difficult to use.

**Comment by jvoltci** [comment]
Hi Sami,

Thank you for letting me know. I will surely look into it and get back to
you with a resolution.

Best,
Jai

**Comment by rafabulsing** [comment]
+1

**Comment by Dracrius** [comment]
I'm guessing this is just dead now? Not having access to the wiki and no fix to a simple "woops I changed a repo setting" issue for almost 2 years is kind of telling. I was getting excited when I found this on pub.dev!!!

**Comment by jvoltci** [comment]
The functionality of this Flutter package is **straightforward** and well-demonstrated in the pub package examples. Given its **simplicity**, a dedicated wiki may be unnecessary. Feel free to explore the package through the provided examples – they should provide ample guidance. If you would like to contribute to it. You are welcome.

**Comment by jvoltci** [comment]
Closing as resolved from last comment.

**Comment by Dracrius** [comment]
... You do realize every part of the git page and pub.dev point to said wiki that already must have existed and can be reenabled here!! 

![image](https://github.com/ivehement/saf/assets/26284634/1c93c6bc-53d5-4fc3-a578-da54de06c6f8)

**Comment by Dracrius** [comment]
![image](https://github.com/ivehement/saf/assets/26284634/ddaff094-fa88-4872-9a81-a7916a226365)
![image](https://github.com/ivehement/saf/assets/26284634/493c5274-a897-4766-a8ee-abd25ef343b0)

**Comment by Dracrius** [comment]
This is not a closed issue haha this is a huge confusion point and a pointless one!

**Comment by Dracrius** [comment]
Every link on both pages goes to this missing wiki...
